[images]
  remote_images = ["https://source.unsplash.com/.*", "https://images.unsplash.com/.*", "https://ext.same-assets.com/.*", "https://ugc.same-assets.com/.*"]

[build]
  command = "bun run build"
  publish = "out"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"

# Cấu hình xử lý form
[build.processing.html]
  pretty_urls = true

# Cấu hình redirects cho xử lý form
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cấu hình form Netlify
[forms]
  [forms.contact]
    name = "contact"
    success_url = "/contact/thanks"

[[plugins]]
  package = "@netlify/plugin-nextjs"
